### ISSUE TITLE
About The Dataset

### ISSUE THREAD

**Issue by bzhaoland** [King-Smalla/LISTA-CE#1]
Hello, Thanks for the detailed code.
But I have a question about the dataset. How does the data (used in training and tesing) generated? Simulation or real world data?

**Comment by King-SmallA** [comment]
The dataset is generated through simulation. The S-V channel model is utilized, and the details are introduced in the corresponding paper.



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 18, 2023 21:57 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [King-Smalla/LISTA-CE] About The Dataset (Issue #1)




 
Hello, Thanks for the detailed code.
 But I have a question about the dataset. How is the data (used in training and tesing) generated? Simulation or real world data?

**Comment by bzhaoland** [comment]
Copy that. Thanks for your reply!




Nature
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "King-Smalla/LISTA-CE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [King-Smalla/LISTA-CE] About The Dataset (Issue #1)





 The dataset is generated through simulation. The S-V channel model is utilized, and the details are introduced in the corresponding paper. 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Tue, Apr 18, 2023 21:57 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;; 
 Subject: [King-Smalla/LISTA-CE] About The Dataset (Issue #1) 
 
 
 
 
   
 Hello, Thanks for the detailed code. 
  But I have a question about the dataset. How is the data (used in training and tesing) generated? Simulation or real world data?
