### ISSUE TITLE
About the layer order and Nc/Nt usage problem in the code.

### ISSUE THREAD

**Issue by bzhaoland** [King-Smalla/LISTA-CE#2]
Dear author, i have run the code in the repo and it successfully run. But i encountered two problems below:

1. Question about the layer index used in the code.
I have noticed that the layer index (layer_num) used in the function `inferance_ista` in file "LISTA_CE_SingleNet.py"  began from 0, so generated a integer sequence ranging from 0 to 19 (included). Resulting in the layer index (the `layer_num` parameter passed in `ista_block` function) starting from 0 too, which caused the module processing order changed from $\mathbf{R}^{(t)} \rightarrow \hat{\mathbf{H}}^{t} \rightarrow \mathbf{R}^{'(t)} \rightarrow \hat{\mathbf{H}}^{'(t)}$ to $\mathbf{R}^{'(t)} \rightarrow \hat{\mathbf{H}}^{'(t)} \rightarrow \mathbf{R}^{(t)} \rightarrow \hat{\mathbf{H}}^{(t)}$. Besides, i ran the code with a layer index sequence begining at 1 ([1, 2, ..., 20]), and found that the code can running too.

code seggment of function `ista_block`:

```python3
def ista_block(Hv, layer_num, W, s, Phi_tf):  # Construct half layer of LISTA_CE
    with tf.variable_scope('layer_%d' % layer_num, reuse=reuse):
        rho = tf.Variable(0.15, dtype=fdtype, name='rho')
        theta = tf.Variable(0.15, dtype=fdtype, name='theta')
    r = Hv + rho * tf.matmul(s - function_g(Hv, Phi_tf), W)
    Hv_k = function_fd(function_soft(function_fs(r, layer_num), theta), layer_num)
    Hv_k_output = r + Hv_k
    return Hv_k_output
```
code seggment of function `inference_ista`, and `max_iteration` in the code equals to `args.layers` which is assigned by user and defaults to 20:

```python3
def inference_ista():   # LISTA_CE
    Hv_hat = []
    Hv0 = tf.zeros(tf.shape(Hv_init), dtype=fdtype)
    Hv_hat.append(Hv0)
    W = tf.transpose(Phi_tf)
    s = function_g(Hv_init, Phi_tf)
    s = s + tf.random_normal(shape=tf.shape(s), dtype=fdtype) * sigma_w
    for i in range(max_iteration):
        Hv_hat_k = ista_block(Hv_hat[-1], i, W, s, Phi_tf)
        Hv_hat.append(Hv_hat_k)
    return Hv_hat
```

So, i get the conclusion that the processing order of the layers in the code doesn't matter the results. Is this correct? Or maybe something gone wrong within my thinking.

2. Question about the number of transmitting antennas (Nt) and number of subcarriers (Nc) in the code.
There are two transpose oprations in `function_fs` and `function_fd` respectively, and the two function correspond to the transformation and inverse transformation in the paer.

I studied the code, and found that the two halves (`x_left` & `x_left`) of the feeded `x` in the code are seperated by the variable `Nt` meaning number of transmitting antennas but should be `Nc` corresponding to number of subcarries (M) according to the paper.

Due to the equivalence of `Nt` and `Nc` (both equals to 32 in LISTA-CE model), the interchangeablely use in the code does not affect the running and results, which may be difference with a different setting such as `Nc = 32` and `Nt = 16`.

I don't know if this is intended and it lurked in my mind for a long time. Appreciate if u can solve this problem for me. Thank you!

Definition of transformation in the code:

```python3
def function_fs(x, layer_num):  # Transformation, F, in equ.(12)
    '''
    complex_label * Nt --> 256
    '''
    input_dim = complex_label * Nt
    hidden_dim = 128
    output_dim = 256
    if layer_num % 2 == 0:  # Trans in equ.(16)
        x = tf.reshape(x, [-1, Nc, input_dim])
        x_left= x[:, :, 0:Nt]
        x_right = x[:, :, Nt:]
        x_left = tf.transpose(x_left, perm=[0, 2, 1])
        x_right = tf.transpose(x_right, perm=[0, 2, 1])
        x = tf.concat([x_left, x_right], 2)
    x = tf.reshape(x, [-1, input_dim])
    with tf.variable_scope('layer_%d/fs.1' % layer_num, reuse=reuse):
        w = variable_w([input_dim, hidden_dim])
        b = variable_b([hidden_dim])
        l = tf.nn.relu(tf.matmul(x, w) + b)
    with tf.variable_scope('layer_%d/fs.2' % layer_num, reuse=reuse):
        w = variable_w([hidden_dim, output_dim])
        b = variable_b([output_dim])
        l_out = tf.matmul(l, w) + b
    return l_out
```

Definition of inverse transformation in the code:

```python3
def function_fd(x, layer_num):  # Invert transformation, \tilde{F}, in equ.(12)
    '''
    256 --> complex_label * Nt
    '''
    input_dim = 256
    hidden_dim = 128
    output_dim = complex_label * Nt
    with tf.variable_scope('layer_%d/fd.1' % layer_num, reuse=reuse):
        w = variable_w([input_dim, hidden_dim])
        b = variable_b([hidden_dim])
        l = tf.nn.relu(tf.matmul(x, w) + b)
    with tf.variable_scope('layer_%d/fd.2' % layer_num, reuse=reuse):
        w = variable_w([hidden_dim, output_dim])
        b = variable_b([output_dim])
        l = tf.matmul(l, w) + b
    if layer_num % 2 == 0:  # # Trans' in equ.(16)
        l = tf.reshape(l, [-1, Nc, output_dim])
        x_left= l[:, :, 0:Nt]
        x_right = l[:, :, Nt:]
        x_left = tf.transpose(x_left, perm=[0, 2, 1])
        x_right = tf.transpose(x_right, perm=[0, 2, 1])
        l = tf.concat([x_left, x_right], 2)
    x_recon = tf.reshape(l, [-1, Nc * output_dim])
    return x_recon
```

**Comment by King-SmallA** [comment]
Thank you for your comments. I appreciate your thorough analysis of the code and your effort to understand each line. I think you will be successful in your research one day.

Since the code was submitted approximately two years ago, I cannot recall all the specific details. When I uploaded the code, I made certain modifications and deletions to enhance its clarity and readability. I believe you can further modify the code based on your understanding.

Regarding your first question, you can attempt to run the code with a layer index sequence starting at 1. I believe you will obtain similar results.  As for your second question, it is important to note that the sequence of matrices in the code does not align with that described in the papers. For instance, in the paper, 'Y = WH' is implemented as 'Y = HW' in the code. These two representations are equivalent if a transpose operation is applied. Therefore, I believe this may be the reason for it being separated by the variable Nt instead Nc. The update sequence might also be a consequence of this equivalence. I encourage you to verify this hypothesis by investigating it further.

**Comment by bzhaoland** [comment]
Thanks for the reply. I will investigate it further.
